using CustomControls;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using YATE.Disassembler;
using YATE.Emulator.Z80CPU;
using YATE.Managers;
using YATECommon;
using YATECommon.Helpers;

namespace YATE.Controls
{
  public partial class DisassemblyListBox : ListBox, INotifyPropertyChanged
  {
    #region · Data members ·

    private int m_tstate_min;
    private int m_tstate_max;
    private string m_tstate_sum_string;
    private AnnotatedScrollBar m_vertical_scroll_bar;
    private TVCMemoryType m_memory_type = TVCMemoryType.RAM;

    #endregion

    #region · Properties ·

    public string TstateSumString
    {
      get
      {
        return m_tstate_sum_string;
      }
      private set
      {
        m_tstate_sum_string = value;
        OnPropertyChanged();
      }
    }

    public TVCMemoryType MemoryType
    {
      get
      {
        return m_memory_type;
      }

      set
      {
        m_memory_type = value;
      }
    }


    #endregion

    #region · Constructor ·

    /// <summary>
    /// Default constructor
    /// </summary>
    public DisassemblyListBox()
    {
      m_tstate_min = 0;
      m_tstate_max = 0;
      m_tstate_sum_string = "0/0";

      SelectionMode = SelectionMode.Extended;

      if ((BreakpointManager)TVCManagers.Default.BreakpointManager != null)  // check for null because of the GUI editor
        ((BreakpointManager)TVCManagers.Default.BreakpointManager).Breakpoints.CollectionChanged += Breakpoints_CollectionChanged;
    }

    #endregion

    #region · Event handlers ·      

    protected override void OnInitialized(EventArgs e)
    {
      base.OnInitialized(e);
    }

    protected override void OnMouseUp(MouseButtonEventArgs e)
    {
      base.OnMouseUp(e);

      // find which element in ListboxItem generated the event
      if(e.OriginalSource != null)
      {
        if(e.OriginalSource is FrameworkElement)
        {
          FrameworkElement element = e.OriginalSource as FrameworkElement;

          while (element != null && element != this)
          {
            // The event is generated by the address part
            if (element.Name == "PART_LineAddress")
            {
              DisassemblyLine current_line = SelectedItem as DisassemblyLine;

              if (current_line != null && current_line.Type == DisassemblyLine.DisassemblyLineType.Disassembly)
              {
                BreakpointInfo breakpoint = new BreakpointInfo(m_memory_type, (ushort)current_line.DisassemblyInstruction.Address);

                if (current_line.IsBreakpoint)
                {
                  ((BreakpointManager)TVCManagers.Default.BreakpointManager).RemoveBreakpoint(breakpoint);
                }
                else
                {
                  ((BreakpointManager)TVCManagers.Default.BreakpointManager).AddBreakpoint(breakpoint);
                }
                break;
              }
            }

            // The click is generated by the operand1 or oeprand 2
            if(element.Name== "PART_Operand1" || element.Name == "PART_Operand2")
            {
              DisassemblyLine current_line = SelectedItem as DisassemblyLine;

              if (current_line != null && current_line.Type == DisassemblyLine.DisassemblyLineType.Disassembly && current_line.DisassemblyInstruction.OpCode != null)
              {
                // The event is only interesting when opcode is jump  or call
                if (current_line.DisassemblyInstruction.OpCode.Flags.HasFlag(Z80DisassemblerTable.OpCodeFlags.Jumps) || current_line.DisassemblyInstruction.OpCode.Flags.HasFlag(Z80DisassemblerTable.OpCodeFlags.Call))
                {
                  // if opcode has two operands only the second operand event is interesting, it it has one operand, only the event of the first operand is interesting
                  if (((string.IsNullOrEmpty(current_line.DisassemblyInstruction.Operand2) && element.Name == "PART_Operand1") ||
                       (!string.IsNullOrEmpty(current_line.DisassemblyInstruction.Operand2) && element.Name == "PART_Operand2")) &&
                      (current_line.DisassemblyInstruction.NextAddress2 != null))
                  {
                    // Change selected item
                    SelectItemAtAddress((ushort)current_line.DisassemblyInstruction.NextAddress2);
                  }
                }
              }
              break;
            }

            // try with parent if original source is not any of the known element
            element = (FrameworkElement)VisualTreeHelper.GetParent(element);

            // end of the test is ListboxItem (considered as top level parant for this event) is reached 
            if (element is ListBoxItem)
              break;
          }
        }
      }
    }

    protected override void OnSelectionChanged(SelectionChangedEventArgs e)
    {
      base.OnSelectionChanged(e);

      for (int i = 0; i < e.AddedItems.Count; i++)
      {
        DisassemblyLine item = (DisassemblyLine)e.AddedItems[i];

        m_tstate_min += (int)item.DisassemblyInstruction.TStates;

        if (item.DisassemblyInstruction.TStates2 > 0)
          m_tstate_max += (int)item.DisassemblyInstruction.TStates2;
        else
          m_tstate_max += (int)item.DisassemblyInstruction.TStates;
      }

      for (int i = 0; i < e.RemovedItems.Count; i++)
      {
        DisassemblyLine item = (DisassemblyLine)e.RemovedItems[i];

        m_tstate_min -= (int)item.DisassemblyInstruction.TStates;

        if (item.DisassemblyInstruction.TStates2 > 0)
          m_tstate_max -= (int)item.DisassemblyInstruction.TStates2;
        else
          m_tstate_max -= (int)item.DisassemblyInstruction.TStates;
      }

      TstateSumString = string.Format("{0}/{1}", m_tstate_min, m_tstate_max);
    }

    #endregion

    #region · Public members ·

    /// <summary>
    /// Finds line at the given memory address
    /// </summary>
    /// <param name="in_address"></param>
    /// <returns></returns>
    public int FindLineAtAddress(ushort in_address)
    {
      DisassemblyLine search = new DisassemblyLine();
      search.DisassemblyInstruction.Address = in_address;

      return (ItemsSource as List<DisassemblyLine>).IndexOf(search);
    }

    public void AddBreakpointToLine(int in_line_index)
    {
      (ItemsSource as List<DisassemblyLine>)[in_line_index].IsBreakpoint = true;
      m_vertical_scroll_bar.AddAnnotation(in_line_index, false, Brushes.Red);
    }

    #endregion

    #region · Non-public members ·

    internal void SetVerticalScrollBar(AnnotatedScrollBar in_scroll_bar)
    {
      m_vertical_scroll_bar = in_scroll_bar;
    }

    private void SelectItemAtAddress(ushort in_address)
    {
      int index = FindLineAtAddress(in_address);

      if (index >= 0)
      {
        SelectedIndex = index;
        this.ScrollToCenterOfView(SelectedItem, false);
      }
    }

    private void Breakpoints_CollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
    {
      switch(e.Action)
      {
        case  System.Collections.Specialized.NotifyCollectionChangedAction.Add:
          foreach (BreakpointInfo breakpoint in e.NewItems)
          {
            if (breakpoint.MemoryType == m_memory_type)
            {
              int line_index = FindLineAtAddress(breakpoint.Address);

              if (line_index >= 0)
              {
                (ItemsSource as List<DisassemblyLine>)[line_index].IsBreakpoint = true;
                m_vertical_scroll_bar.AddAnnotation(line_index, false, Brushes.Red);
              }
            }
          }
          break;
         
        case System.Collections.Specialized.NotifyCollectionChangedAction.Remove:
          foreach (BreakpointInfo breakpoint in e.OldItems)
          {
            if (breakpoint.MemoryType == m_memory_type)
            {
              int line_index = FindLineAtAddress(breakpoint.Address);

              if (line_index >= 0)
              {
                (ItemsSource as List<DisassemblyLine>)[line_index].IsBreakpoint = false;
                m_vertical_scroll_bar.RemoveAnnotation(line_index, false, Brushes.Red);
              }
            }
          }
          break;

        case System.Collections.Specialized.NotifyCollectionChangedAction.Reset:
          foreach(DisassemblyLine line in ItemsSource as List<DisassemblyLine>)
          {
            line.IsBreakpoint = false;
            m_vertical_scroll_bar.RemoveAnnotation(line.Index, false, Brushes.Red);
          }
          break;
      }
    }

    #endregion

    #region · INotifyPropertyChanged interface ·

    public event PropertyChangedEventHandler PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
      if (PropertyChanged != null && propertyName != null)
        PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    }

    #endregion
  }
}